// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scola;

#nullable disable

namespace Scola.Migrations
{
    [DbContext(typeof(ScolaBaseContext))]
    [Migration("20240302195527_InidioDoProjeto")]
    partial class InidioDoProjeto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");
#pragma warning restore 612, 618
        }
    }
}
